# Generated by Django 4.0.1 on 2022-05-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='added',
        ),
        migrations.AddField(
            model_name='employee',
            name='professors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.faculty'),
            preserve_default=False,
        ),
    ]
