# Generated by Django 4.0.1 on 2022-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_employee_added_employee_professors'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approve',
            field=models.CharField(default='Hold', editable=False, max_length=20),
        ),
    ]
