# Generated by Django 4.0.1 on 2022-03-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_employee_bank_account_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='from_date',
        ),
    ]
