# Generated by Django 4.0.1 on 2022-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='approve',
            field=models.CharField(default='Hold', max_length=20),
        ),
    ]
