# Generated by Django 4.0.1 on 2022-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_hire_date_employee_from_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RndAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
    ]
